java_test(
    name = "greeter_test",
    srcs = ["GreeterTest.java"],
    test_class = "com.example.GreeterTest",
    deps = [
        "//src/main/java/com/example:greeter",
        "@maven//:junit_junit",
    ],
)
